# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rb_sys/extensiontask'

task build: :compile

GEMSPEC = Gem::Specification.load('auth.gemspec')

RbSys::ExtensionTask.new('auth', GEMSPEC) do |ext|
  ext.lib_dir = 'lib/auth'
end

task default: :compile
