# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rb_sys/extensiontask'

task build: :compile

GEMSPEC = Gem::Specification.load('email.gemspec')

RbSys::ExtensionTask.new('email', GEMSPEC) do |ext|
  ext.lib_dir = 'lib/email'
end

task default: :compile
