# frozen_string_literal: true

require 'bundler/gem_tasks'
require 'rb_sys/extensiontask'

task build: :compile

GEMSPEC = Gem::Specification.load('model.gemspec')

RbSys::ExtensionTask.new('model', GEMSPEC) do |ext|
  ext.lib_dir = 'lib/model'
end

task default: :compile
