module Auth
  VERSION: String
end

module SmbCloud
  module Auth
    class Error < StandardError
      attr_reader error_code: Integer?
      attr_reader payload: untyped
    end

    module Environment
      DEV: String
      PRODUCTION: String
    end

    class Client
      attr_reader environment: String
      attr_reader app_id: String
      attr_reader app_secret: String

      def initialize: (environment: String, app_id: String, app_secret: String) -> void
      def signup: (email: String, password: String) -> Hash[Symbol, untyped]
      def login: (email: String, password: String) -> Hash[Symbol, untyped]
      def me: (access_token: String) -> Hash[Symbol, untyped]
      def logout: (access_token: String) -> bool
      def remove: (access_token: String) -> bool
    end

    def self.client: (environment: String, app_id: String, app_secret: String) -> Client
    def self.signup_with_client: (environment: String, app_id: String, app_secret: String, email: String, password: String) -> Hash[Symbol, untyped]
    def self.login_with_client: (environment: String, app_id: String, app_secret: String, email: String, password: String) -> Hash[Symbol, untyped]
    def self.me_with_client: (environment: String, app_id: String, app_secret: String, access_token: String) -> Hash[Symbol, untyped]
    def self.logout_with_client: (environment: String, app_id: String, app_secret: String, access_token: String) -> bool
    def self.remove_with_client: (environment: String, app_id: String, app_secret: String, access_token: String) -> bool
  end
end
