name: Tests

# This workflow run tests for each push

on: push

env:
  CLI_CLIENT_SECRET: ${{ secrets.CLI_CLIENT_SECRET }}

jobs:
  test_branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@stable

      - run: cargo test --all-features
